export enum ExamsEnum {
  ABDMO = 'Abdominoscopia',
  ABREU = 'Abreugrafia',
  ADENO = 'Adenograma',
  ANXFR = 'Analise_molecular_para_a_sindrome_do_X_fragil',
  ANTBI = 'Antibiograma',
  ANUSC = 'Anuscopia',
  BIOPS = 'Biopsia',
  CALCE = 'Calcemia',
  CAPNO = 'Capnometria',
  CRVIR = 'Carga_viral',
  CARGU = 'Cartao_de_Guthrie',
  CATET = 'Cateterismo',
  CISTO = 'Cistocentese',
  CITFL = 'Citometria de fluxo',
  COAGU = 'Coagulograma',
  COLON = 'Colonoscopia',
  CODIF = 'Coloração_diferencial',
  CORSU = 'Corante Sudan',
  CULDO = 'Culdoscopia',
  CURB6 = 'CURB_65',
  DENOS = 'Densitometria_Ossea',
  DERMA = 'Dermatoscopia',
  DITEX = 'Dieta_de_exclusao',
  DORMI = 'Doenca_residual_minima',
  DOPTC = 'Doppler_transcraniano',
}
