import {
  faUserEdit,
  faLock,
  faCrown,
  faCalendarPlus,
  faFileMedicalAlt,
  faHistory,
  faClipboardCheck,
  faUserPlus,
  faCalendarAlt,
  faIdCard,
} from "@fortawesome/free-solid-svg-icons";

import {
  faPlus,
  faPowerOff,
  faHome,
  faUser,
  faFileMedical,
  faFileInvoiceDollar,
  faBookMedical,
  faCalendarCheck,
  faPoll,
  faBell,
  faCommentAlt,
  faEllipsisH,
  faClock,
  faCalendarDay,
  faSignOutAlt,
  faUsersCog,
  faUserMd,
  faConciergeBell,
  faUserCog,
  faFlask,
  faHeartbeat,
  faHouseUser,
  faPortrait,
  faSearch,
  faChartBar,
} from "@fortawesome/free-solid-svg-icons";

export const Buttons = {
  profile: [
    { icon: faUserEdit, path: "edit-profile" },
    { icon: faIdCard, path: "identification" },
    { icon: faHouseUser, path: "edit-address" },
    { icon: faPortrait, path: "edit-avatar" },
    { icon: faLock, path: "security" },
    { icon: faPowerOff, path: "unsubscribe" },
  ], //
  owner: [
    { icon: faChartBar, path: "dashboard" },
    { icon: faUserMd, path: "doctors" },
    { icon: faUserCog, path: "managers" },
    { icon: faCrown, path: "owners" },
    { icon: faSearch, path: "search" },
  ],
  client: [
    { icon: faChartBar, path: "dashboard" },
    { icon: faFileMedicalAlt, path: "exams" },
    { icon: faBookMedical, path: "history" },
  ],
  recept: [
    { icon: faUserPlus, path: "add-client" },
    { icon: faClipboardCheck, path: "verify" },
    { icon: faCalendarDay, path: "appointments" },
    { icon: faCalendarPlus, path: "create-appointment" },
  ],
  doctor: [
    { icon: faFileMedical, path: "create-prescription" },
    { icon: faFileMedicalAlt, path: "exams" },
    { icon: faBookMedical, path: "history" },
    { icon: faClock, path: "schedules" },
    { icon: faCalendarPlus, path: "create-schedule" },
  ],
  manager: [
    // { icon: faChartBar, path: "../managers/dashboard" },
    { icon: faFlask, path: "labs" },
    { icon: faConciergeBell, path: "receptionists" },
    { icon: faSearch, path: "search" },
  ],
  lab: [
    { icon: faFileMedical, path: "dashboard" },
    { icon: faClock, path: "exams" },
  ],
};
